version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localdevelopmentonly
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./run.py:/app/run.py
    depends_on:
      - postgres
